<?php

namespace App\Services\Tracking;

use App\Models\AnalyticsEvent;
use App\Models\Pageview;
use App\Models\VisitSession;
use App\Models\Website;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class TrackingIngestionService
{
    /**
     * Persist one validated tracking payload into the analytics tables.
     *
     * This is the main write path for tracker.js. It keeps website discovery,
     * session updates, raw event storage, and pageview projection in one place.
     */
    public function ingest(array $payload, ?string $ipAddress, ?string $userAgent): AnalyticsEvent
    {
        // Create the website on first contact so new embeds appear automatically
        $website = Website::query()->firstOrCreate(
            ['site_id' => $payload['siteId']],
            [
                'name' => Str::headline($payload['siteId']),
                'domain' => parse_url($payload['referrer'] ?? '', PHP_URL_HOST) ?: 'unknown.local',
                'timezone' => $payload['timezone'] ?? config('app.timezone'),
            ],
        );

        // Keep the website timezone aligned with the site that is sending events
        if (($payload['timezone'] ?? null) && $website->timezone !== $payload['timezone']) {
            $website->forceFill(['timezone' => $payload['timezone']])->save();
        }

        $occurredAt = Carbon::parse($payload['timestamp'] ?? now());

        // Session keys are generated by tracker.js and scoped per website
        $session = VisitSession::query()->updateOrCreate(
            [
                'website_id' => $website->id,
                'session_key' => $payload['sessionId'],
            ],
            [
                'visitor_id' => $payload['visitorId'],
                'started_at' => $occurredAt,
                'last_seen_at' => $occurredAt,
                'referrer' => $payload['referrer'] ?? null,
                'browser' => $payload['browser'] ?? $this->guessBrowser($userAgent),
                'device' => $payload['device'] ?? 'desktop',
            ],
        );

        // Store the normalized event before creating feature-specific projections
        $event = AnalyticsEvent::query()->create([
            'website_id' => $website->id,
            'session_id' => $session->id,
            'type' => $payload['type'],
            'pathname' => $payload['pathname'],
            'referrer' => $payload['referrer'] ?? null,
            'browser' => $payload['browser'] ?? $this->guessBrowser($userAgent),
            'device' => $payload['device'] ?? 'desktop',
            'screen' => $payload['screen'] ?? null,
            'occurred_at' => $occurredAt,
            'metadata' => [
                ...($payload['metadata'] ?? []),
                // Store a salted hash instead of the raw IP address
                'ip_hash' => $ipAddress ? hash('sha256', $ipAddress.config('app.key')) : null,
            ],
        ]);

        // Pageviews get their own table because most dashboard queries start there
        if ($payload['type'] === 'pageview') {
            Pageview::query()->create([
                'website_id' => $website->id,
                'session_id' => $session->id,
                'pathname' => $payload['pathname'],
                'title' => $payload['title'] ?? null,
                'referrer' => $payload['referrer'] ?? null,
                'viewed_at' => $occurredAt,
            ]);
        }

        return $event;
    }

    /**
     * Derive a simple browser label when the tracker payload does not include one.
     */
    private function guessBrowser(?string $userAgent): string
    {
        return match (true) {
            str_contains((string) $userAgent, 'Firefox') => 'Firefox',
            str_contains((string) $userAgent, 'Edg') => 'Edge',
            str_contains((string) $userAgent, 'Chrome') => 'Chrome',
            str_contains((string) $userAgent, 'Safari') => 'Safari',
            default => 'Unknown',
        };
    }
}
